# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- wyam

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Install Wyam'
  inputs:
    command: custom
    custom: 'tool'
    arguments: 'install -g Wyam.tool'

- bash: $HOME/.dotnet/tools/wyam
  displayName: 'Generate site'

- task: CopyFiles@2
  inputs:
    sourceFolder: './output'
    #contents: '**' 
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true # Optional
    #overWrite: false # Optional
    #flattenFolders: false # Optional

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: site
